name: on-push

on: pull_request

env:
    PNPM_VERSION: 10.24.0
    NODE_VERSION: 24.11.1
    YQ_VERSION: v4.44.3
    CBOR_VERSION: v0.5.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm
      
      - name: Install cbor
        uses: jaxxstorm/action-install-gh-release@v2.1.0
        with:
          repo: ironspecs/cbor-cli
          tag: ${{ env.CBOR_VERSION }}
          cache: enable
      
      - name: Install yq
        uses: jaxxstorm/action-install-gh-release@v2.1.0
        with:
          repo: mikefarah/yq
          tag: ${{ env.YQ_VERSION }}
          cache: enable

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Setup Mocks
        run: |
          ./scripts/xspf-to-cbor.sh ./test/resources/DeepHouse2025.xspf

      - name: Build
        run: pnpm run build

      - name: Test
        run: pnpm test
